### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by auwtch** [qor/bindatafs#2]
I made all steps, after remove github.com/qor/admin and an app didn't run

**Comment by ErhanAbi** [comment]
Hi @DenisNeustroev, It should work but I'm not sure if running `go run -tags bindatafs main.go` should do the trick.

But it works if you first run `go run main.go --compile-qor-templates` -- and make sure that the templates folder is generated where all the assets from qor will be added, and also, make sure that the templates_bindatafs.go file is generated (this one is the only file needed in production).

Then, you can build the project using the `bindatafs` tag: `go build -tags bindatafs`.
From the same folder, start the project by running the generated binary: `./my-qor-program`

Then you can try deleting `github.com/qor/admin` and visit your localhost. Everything should work as if you didn't remove the admin folder.

**Comment by jinzhu** [comment]
@pfzero thank you for your comments.
